---
title: "linear_models"
author: "Guojing Wu"
date: "2018/11/8"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, 
  message = F, 
  warning = F)

library(tidyverse)
library(p8105.datasets)
set.seed(1)
theme_set(theme_bw())
```

SLR / MLR / GLM

## example

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(boro = neighbourhood_group,
         neighborhood = neighbourhood) %>% 
  filter(boro != "Staten Island") %>% 
  select(price, stars, boro, neighborhood, room_type)
```

Fit a model for price as an outcome, and look at the output roughly

```{r}
fit = lm(price ~ stars + boro, data = nyc_airbnb)

summary(fit)
summary(fit)$coef
coef(fit)
fitted.values(fit)
```

using broom for a better summary

```{r}
fit %>% 
  broom::tidy() %>% 
  select(term, estimate, p.value) %>% 
  mutate(term = str_replace(term, "^boro", "Boro: ")) %>% 
  knitr::kable(digits = 3)
```

Look at some other summary

```{r}
fit %>% 
  broom::glance()
```

Be careful with factors

```{r}
nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(boro = fct_infreq(boro), # change to factor and order the level based on frequency
         room_type = fct_infreq(room_type))

fit = lm(price ~ stars + boro, data = nyc_airbnb)

fit %>% 
  broom::tidy()
```

